version: "3.9"

services:
  app:
    build: ./
    ports:
      - 9000:9000
    environment:
      # Laravel 用の環境変数例
      APP_ENV: local
      APP_DEBUG: 1
    # 開発時のみ有効
    volumes:
      # - ./note-app:/workdir/note-app
      - ./note-app/vendor:/workdir/note-app/vendor

  db:
    image: mysql:8.3
    volumes:
      - ./laravel_app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306