version: "3.9"

services:
  app:
    build: ./
    ports:
      - 9000:9000
    environment:
      APP_ENV: local
      APP_DEBUG: 1
    volumes:
      - ./note-app:/workdir/note-app   # ←これ1行だけで十分！

  db:
    image: mysql:8.3
    volumes:
      - ./laravel_app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306